# Generated by Django 4.0 on 2023-10-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='services',
            field=models.ManyToManyField(related_name='devices', to='devices.Service'),
        ),
    ]
